### ISSUE TITLE
Is it possible to use different models?

### ISSUE THREAD

**Issue by JuanDavidG1997** [lehduong/GINP#1]
I am trying to prune a resnet18 trainen on cifar10 usign weight pruning. Is it possible with your repository?

**Comment by lehduong** [comment]
Hi @JuanDavidG1997, since the weight pruning is quiet flexible, it should work with any models. That being said, if you want to use your pretrained weight/different architectures, you might have to modify some parts of the code in order to load desired checkpoint. I think you can simply add *resnet18* to `models/__init__.py` to make it work.
